### PR TITLE
Siege Of Niuzao Temple

### PR DESCRIPTION
**Pull request by Dieguitox87**
Need some adjustments

### CODE REVIEW

**Comment by cybrann** [comment]
I don't understand what you did here. Spawns? Also why are you deleting stuff from creature_template?

**Comment by Dieguitox87** [comment]
Will first i put all the npc in place thats the "spawns". Then the deleting stuff is for ppl that might do some work in their db and replace it for my work. Sad that you wont merge it. Try it

**Comment by cybrann** [comment]
Ok but optimize queries first. You made so many delete + insert queries when 1 delete and 1 insert query is enough per table. Do it like this:

DELETE FROM creature WHERE guid IN (list all guids here and separate them by the comma);
INSERT INTO creature VALUES
(put the data here),
(next data here),
.
.
.
(last one like this);

**Comment by Dieguitox87** [comment]
Better?

**Comment by Keital** [comment]
@Dieguitox87 deleting from creature_template isn't a good idea, it's there for a reason and custom modifications to people's own db is just their problem, so just delete and insert if it is "blizzlike" templates that needs to be updated on mopdb

**Comment by Dieguitox87** [comment]
@Keital ok I just made the modifications that you guys told me. Need something more?

**Comment by cybrann** [comment]
This is useless so I will just close it. When you learn a bit more about database then start doing fixes.

**Pull request closed without merging**
